version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis_service
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf  
    ports:
      - "${REDIS_PORT}:6379"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}   
    networks:
      - app-network

  postgres:
    image: postgres:latest
    container_name: postgres_service
    ports:
      - "${PORT_DB}:5432"
    environment:
      POSTGRES_USER: ${USERNAME_DB}
      POSTGRES_PASSWORD: ${PASSWORD_DB}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data  
    networks:
      - app-network

volumes:
  pgdata:  

networks:
  app-network: 
    driver: bridge
